# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: 'follow me on <a href="https://matters.news/@vibertthio">matters</a> & <a href="https://medium.com/@vibertthio">matters</a>'

style: light

plugins:
  - jekyll-seo-tag
